### ISSUE TITLE
Getting Protobuf error on 0.15.0 with python 3.11.9 in docker container

### ISSUE THREAD

**Issue by fingineering** [authzed/authzed-py#165]
## Setup 

I'm running a fastapi API using uvicorn on Python 3.11.9 in a linux/amd64 docker container with an alpine Linux image. 

container image: `audavisaiacr.azurecr.io/customer-configuration-service:latest` to be precise

with python3.11.9 installed via apk

## Symptoms

Running the latest 0.15.0 authzed-py version with protobuf 5.26. or 5.27 results in error on import Client

```
File "/config_service/app/main.py", line 3, in <module>
    from app.routes.user import router as user_router
  File "/config_service/app/routes/user.py", line 7, in <module>
    from app.dependencies import (
  File "/config_service/app/dependencies.py", line 3, in <module>
    from authzed.api.v1 import Client
  File "/usr/local/lib/python3.11/site-packages/authzed/api/v1/__init__.py", line 18, in <module>
    from authzed.api.v1.experimental_service_pb2 import (
  File "/usr/local/lib/python3.11/site-packages/authzed/api/v1/experimental_service_pb2.py", line 15, in <module>
    from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
  File "/usr/local/lib/python3.11/site-packages/google/api/annotations_pb2.py", line 44, in <module>
    google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'MethodOptions' has no attribute 'RegisterExtension'
```

----

It works on MacOS directly with 0.15.0 and 3.11.9 

It works with 0.14.0 and Python 3.11.9 within the same docker container.

I'm not sure how to proceed to fix this.

**Comment by josephschorr** [comment]
Perhaps a cache issue? https://github.com/esphome/issues/issues/5637#issuecomment-2020258132

**Comment by fingineering** [comment]
Maybe kind of a cache issue, just emptying the cache and reinstalling did not help. Needed to build the wheel from the source, which required installing build-base first. 

Not optimal but did result in a working container.

Hence, maybe something in the binary distribution of protobuf?
